# Generated by Django 3.0.2 on 2020-02-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='phone_no',
            new_name='mobile',
        ),
    ]
