# Generated by Django 3.0.2 on 2020-02-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_check_in_data_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
